url: "https://www.atava.io"
baseurl: ""
title: "Atava Inc"
logos:
  dark: "assets/img/atava-black.svg"
  light: "assets/img/atava-white.svg"
favicons:
  svg: "assets/img/atava-favicon.svg"
  ico: "assets/img/atava-favicon.ico"
  touch: "assets/img/atava-touch-icon.png"
plugins:
  - jekyll-postcss
postcss:
  cache: false

sass:
  load_paths:
    - _sass
    - node_modules
include: ["node_modules/tailwindcss"]
